# Generated by Django 4.2.6 on 2023-10-16 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('founder_name', models.CharField(max_length=150)),
                ('principal_name', models.CharField(max_length=150)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(max_length=225)),
                ('email_id', models.EmailField(max_length=254)),
                ('staff_count', models.PositiveSmallIntegerField(default=0)),
                ('students_count', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Institute',
                'verbose_name_plural': 'Institute',
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('qualification', models.TextField()),
                ('department', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField(default=None)),
                ('contact_number', models.CharField(max_length=225)),
                ('email_id', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school_app.institute')),
            ],
            options={
                'verbose_name': 'Teachers',
                'verbose_name_plural': 'Teachers',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('standard', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(default=None)),
                ('contact_number', models.CharField(max_length=225)),
                ('email_id', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school_app.institute')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school_app.teacherprofile')),
            ],
            options={
                'verbose_name': 'Students',
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=None)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school_app.institute')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school_app.studentprofile')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school_app.teacherprofile')),
            ],
            options={
                'verbose_name': 'Certificates',
                'verbose_name_plural': 'Certificates',
            },
        ),
    ]
